import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import adminAuthRoutes from '../modules/admin/admin.routes';
import adminUsersRoutes from '../modules/admin/admin-users.routes';
import adminAvatarsRoutes from '../modules/admin/admin-avatars.routes';
import adminStatsRoutes from '../modules/admin/admin-stats.routes';
import creditRoutes from '../modules/credit/credit.routes';
import seedanceReelRoutes from '../modules/seedance-reel/seedance-reel.routes';
import actionReelRoutes from '../modules/action-reel/action-reel.routes';
import comedyReelRoutes from '../modules/comedy-reel/comedy-reel.routes';
import reAvatarsRoutes from '../modules/re-avatars/re-avatars.routes';
import modelTourRoutes from '../modules/model-tour/model-tour.routes';
import creativeAdsRoutes from '../modules/creative-ads/creative-ads.routes';
import studioRoutes from '../modules/studio/studio.routes';
import agentChatRoutes from '../modules/agent-chat/agent-chat.routes';
import exportsRoutes from '../modules/exports/exports.routes';
import captionsRoutes from '../modules/captions/captions.routes';
import assetRoutes from '../modules/asset/asset.routes';
import userRoutes from '../modules/user/user.routes';
import musicRoutes from '../modules/music/music.routes';
import tempFilesRoutes from '../modules/temp-files/temp-files.routes';
import paymentsRoutes from '../modules/payments/payments.routes';

const router : Router = Router();

router.use('/auth', authRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/admin/users', adminUsersRoutes);
router.use('/admin/avatars', adminAvatarsRoutes);
router.use('/admin/stats', adminStatsRoutes);
router.use('/credits', creditRoutes);
router.use('/seedance-reel', seedanceReelRoutes);
router.use('/action-reel', actionReelRoutes);
router.use('/comedy-reel', comedyReelRoutes);
router.use('/avatars', reAvatarsRoutes);
router.use('/model-tour', modelTourRoutes);
router.use('/creative-ads', creativeAdsRoutes);
router.use('/studio', studioRoutes);
router.use('/agent-chat', agentChatRoutes);
router.use('/exports', exportsRoutes);
router.use('/captions', captionsRoutes);
router.use('/assets', assetRoutes);
router.use('/user', userRoutes);
router.use('/music-library', musicRoutes);
router.use('/temp-files', tempFilesRoutes);
router.use('/payments', paymentsRoutes);

export default router;
